name: OpenWRT - X86 Generic
on:
  push:
    branches:
  watch:
    types: started

env:
  URL: https://git.openwrt.org/openwrt/openwrt.git
  BRANCH: master
  FEEDS_FILE: feeds.conf.default
  CONFIG: x86.config
  P1: diy-part1.sh
  P2: diy-part2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

jobs:
  x86:
    runs-on: ubuntu-latest
    container: sirherobrine23/openwrtbuild-ci:latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Copilando e Organizando os arquivos
      run: |
        start_new

    - name: Definindo Alguns arquivos
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Gerando Tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true'
      run: |
        echo "::set-env name=FILE_DATE::_$(date +"%Y%m%d%H%M")"
        echo ::set-env name=RELEASE_NAME::"$(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")-OpenWrt_WR941NDv3 Copliler 3"
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")"
        echo "OpenWRT build - branch: $BRANCH ,Generic Device X86, Date build: $(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")" >> release.txt
    
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}