name: OpenWRT Github CI
on:
  push:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOADTORELEASE == 'true'
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@main
    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@javascript
      with:
        CONFIG: 'x64.config'
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
